<a href="https://colab.research.google.com/github/Uzma-Jawed/python-class_work-and-practice/blob/main/20_Numpy_array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
data = [1, 2, 3, 4, 5, 6, 7, 8]

In [ ]:
import numpy as np

In [ ]:
array_1 = np.array(data)

In [ ]:
np.array([1, 2, 3])

array([1, 2, 3])

In [ ]:
array_1 = np.array(data)

In [ ]:
array_1.ndim

1

In [ ]:
array_1.dtype

dtype('int64')

In [ ]:
array_2 = np.arange(0, 10, 2)

In [ ]:
array_2

array([0, 2, 4, 6, 8])

In [ ]:
np.zeros((1))

array([0.])

In [ ]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
array_1

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
array_1[4]

np.int64(5)

In [ ]:
array_1[3:6]

array([4, 5, 6])

In [ ]:
array_1[3:6:2] # indexing and slicing

array([4, 6])

In [ ]:
array_1[array_1 > 5]

array([6, 7, 8])

In [ ]:
array_1[array_1 > 5] = 4

In [ ]:
array_1

array([1, 2, 3, 4, 5, 4, 4, 4])

In [ ]:
array_one = np.ones((1, 3))

In [ ]:
array_one

array([[1., 1., 1.]])

In [ ]:
array_one = np.ones((1, 3))

In [ ]:
array_one

array([[1., 1., 1.]])

In [ ]:
array_one[3:6, 3:6]

array([], shape=(0, 0), dtype=float64)

In [ ]:
array_one = np.ones((2, 3))

In [ ]:
array_one

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
[[1., 1., 1.],[1., 1., 1.]]

[[1.0, 1.0, 1.0], [1.0, 1.0, 1.0]]

In [ ]:
array_one[3:6, 3:6]

array([], shape=(0, 0), dtype=float64)

In [ ]:
array_one[1, :]

array([1., 1., 1.])

In [ ]:
array_one[1, 1]

np.float64(1.0)

In [ ]:
# 2D array matrix with 2 rows

arr = np.array([[1,2,3],[4,5,6]])

In [ ]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr[1,1]

np.int64(5)

In [ ]:
arr[1,1:3]

array([5, 6])

In [ ]:
arr[:,1:3]

array([[2, 3],
       [5, 6]])

In [ ]:
# create 2 dimensions

np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [ ]:
array_4[0, 0] = 1
array_4[1, 1] = 1
array_4

array([[1., 0.],
       [0., 1.]])

In [ ]:
# using slicing and np.arange

array_4[np.arange(2), np.arange(2)] = 1
array_4

array([[1., 0.],
       [0., 1.]])

In [ ]:
# using np.eye

array_4 = np.eye(2)

In [ ]:
array_4

array([[1., 0.],
       [0., 1.]])

In [ ]:
arr_2 = np.zeros((2, 2))  # create a 2x2 matrix of zeros
arr_2[1, 0] = 1
arr_2[0, 1] = 1

In [ ]:
arr_2

array([[0., 1.],
       [1., 0.]])

In [ ]:
# create np.array with 9 values

np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
# Create 2D

np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
# create 3D

np.arange(9).reshape(1,3,3)

array([[[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]])

In [ ]:
np.arange(16)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [ ]:
arr_3 = np.arange(16).reshape(2,2,4)

In [ ]:
arr_3

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

📚 Explanation of Dimensions & Channels
Shape of arr_3: (2, 2, 4)


• 1st dimension (axis 0): 2 blocks, often called depth or batch



• 2nd dimension (axis 1): 2 rows per block



• 3rd dimension (axis 2): 4 columns per row



~ Channel Analogy (like in images):
If you were dealing with image data:



• Shape (2, 2, 4) could mean:



• 2 images (or data slices)



• Each with 2 rows



• Each row having 4 values (like RGB channels or pixel intensities)

In [ ]:
arr_3[0]

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [ ]:
arr_3[0, 1]

array([4, 5, 6, 7])

In [ ]:
arr_3[0, 1, 1]

np.int64(5)

In [ ]:
# 2nd & 3rd row

arr_3[0:,1]

array([[ 4,  5,  6,  7],
       [12, 13, 14, 15]])

In [ ]:
# get 5, 6, 13, 14

arr_3[:,1, 1:3]

array([[ 5,  6],
       [13, 14]])

___
Explanation: This selects: all blocks (:), row 1 (1), columns 1 to 2 (1:3)
___

In [85]:
np.arange(16).reshape(1,4,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [86]:
np.arange(16).reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [87]:
np.arange(12).reshape(1,3,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

In [88]:
np.arange(12).reshape(2,2,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [ ]:
arr = [[1,2,3],[4,5,6]]

In [ ]:
arr_np = np.array(arr)

In [ ]:
arr_np + 4         # Add 4 to each element

array([[ 5,  6,  7],
       [ 8,  9, 10]])

In [83]:
arr_np * 5          # multiply each element by 5

array([[ 5, 10, 15],
       [20, 25, 30]])

In [84]:
arr_np.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])